Repository RunnersHi/RunnersHi_iOS, pull requests merged in 2021-03, with the labels that each got.

#16 [3/25] MypageVC Refactoring
  Runners_Hi/Podfile.lock
  Runners_Hi/Runners_Hi/Resource/StoryBorads/MyPageTab.storyboard
  Runners_Hi/Runners_Hi/Source/Cell/GenderSelectCell.swift
  Runners_Hi/Runners_Hi/Source/ViewController/MyPageVC.swift
  Runners_Hi/Runners_Hi/Source/ViewController/SignUpVC.swift
Labels: iOS🍎, refact🪓, 영재🦝

#15 [3/25] MainVC Code Refactoring
  Runners_Hi/Podfile.lock
  Runners_Hi/Runners_Hi/Resource/StoryBorads/RunningTab.storyboard
  Runners_Hi/Runners_Hi/Source/Cell/GenderSelectCell.swift
  Runners_Hi/Runners_Hi/Source/ViewController/MainVC.swift
  Runners_Hi/Runners_Hi/Source/ViewController/SignUpVC.swift
Labels: iOS🍎, refact🪓, 민희🐯

#20 [03/26] MypageVC 리팩토링
  Runners_Hi/Podfile.lock
  Runners_Hi/Runners_Hi/Source/Cell/MyProfileHeader.swift
  Runners_Hi/Runners_Hi/Source/ViewController/MyPageVC.swift
  Runners_Hi/Runners_Hi/Supporting File/Info.plist
Labels: iOS🍎, refact🪓, 영재🦝

#19 [3/26] UIFont, UILabel Extension 만들기
  Runners_Hi/Runners_Hi.xcodeproj/project.pbxproj
  Runners_Hi/Runners_Hi/Source/Cell/PopUpCell.swift
  Runners_Hi/Runners_Hi/Source/Extensions/UIFont+Extension.swift
  Runners_Hi/Runners_Hi/Source/Extensions/UILabel+Extension.swift
  Runners_Hi/Runners_Hi/Source/ViewController/MainVC.swift
Labels: iOS🍎, new🪄, refact🪓, 민희🐯

#24 [03/27] MypageVC Refactoring3
  Runners_Hi/Runners_Hi/Source/Cell/MyProfileHeader.swift
  Runners_Hi/Runners_Hi/Source/ViewController/MyPageVC.swift
Labels: iOS🍎, refact🪓, 영재🦝

#23 [03/27] MatchingGoalVC Code Refactoring
  Runners_Hi/Runners_Hi/Source/Cell/BattleGoalSelectCell.swift
  Runners_Hi/Runners_Hi/Source/Model/GoalInformation.swift
  Runners_Hi/Runners_Hi/Source/ViewController/MatchingGoalVC.swift
Labels: iOS🍎, refact🪓, 민희🐯

#28 [0328] MyPageVC Refactoring4
  Runners_Hi/Runners_Hi/Source/Cell/MyProfileHeader.swift
  Runners_Hi/Runners_Hi/Source/Cell/ProfileBadgeCell.swift
  Runners_Hi/Runners_Hi/Source/ViewController/MyPageVC.swift
Labels: iOS🍎, refact🪓, 영재🦝

#27 [03/28] UIButton 코드로 구현
  Runners_Hi/Podfile.lock
  Runners_Hi/Runners_Hi/Resource/StoryBorads/RunningTab.storyboard
  Runners_Hi/Runners_Hi/Source/ViewController/MatchingGoalVC.swift
Labels: iOS🍎, new🪄, refact🪓, 민희🐯

#32 [03/29] MyPageVC 폰트 익스텐션 적용
  Runners_Hi/Podfile.lock
  Runners_Hi/Runners_Hi/Source/Cell/MyProfileHeader.swift
  Runners_Hi/Runners_Hi/Source/Cell/ProfileBadgeCell.swift
Labels: iOS🍎, refact🪓, 영재🦝

#31 [03/29] MatchingGenderVC Refactoring
  Runners_Hi/Runners_Hi.xcodeproj/project.pbxproj
  Runners_Hi/Runners_Hi/Source/Cell/BattleGenderSelectCell.swift
  Runners_Hi/Runners_Hi/Source/Extensions/String+Extension.swift
  Runners_Hi/Runners_Hi/Source/Extensions/UILabel+Extension.swift
  Runners_Hi/Runners_Hi/Source/Model/Gender.swift
  Runners_Hi/Runners_Hi/Source/ViewController/FindRunnerVC.swift
  Runners_Hi/Runners_Hi/Source/ViewController/MatchingGenderVC.swift
  Runners_Hi/Runners_Hi/Source/ViewController/SignUpVC.swift
Labels: iOS🍎, refact🪓, 민희🐯

#36 [03/31] myPageVCHeader
  Runners_Hi/Runners_Hi/Resource/Assets.xcassets/graybox1Myprofilefragment.imageset/Contents.json
  Runners_Hi/Runners_Hi/Resource/Assets.xcassets/graybox1Myprofilefragment.imageset/graybox1Myprofilefragment.png
  Runners_Hi/Runners_Hi/Resource/Assets.xcassets/graybox1Myprofilefragment.imageset/graybox1Myprofilefragment@2x.png
  Runners_Hi/Runners_Hi/Resource/Assets.xcassets/graybox1Myprofilefragment.imageset/graybox1Myprofilefragment@3x.png
  Runners_Hi/Runners_Hi/Resource/StoryBorads/MyPageTab.storyboard
  Runners_Hi/Runners_Hi/Source/Cell/MyProfileHeader.swift
Labels: iOS🍎, refact🪓, 영재🦝

#35 [03/31] FineRunnerVC 코드 정리
  Runners_Hi/Runners_Hi/Source/Service/SocketIOManager.swift
  Runners_Hi/Runners_Hi/Source/ViewController/FindRunnerVC.swift
Labels: iOS🍎, refact🪓
